CREATE DATABASE ATIVIDADE_11;

USE ATIVIDADE_11;

CREATE TABLE CLIENTE_REL
(
		CODCLI VARCHAR(15) NOT NULL,
		NOME VARCHAR(100) NOT NULL,
        RUA VARCHAR(100) NOT NULL,
        CIDADE VARCHAR(100) NOT NULL,
        ESTADO CHAR(2) NOT NULL,
        CEP CHAR(10) NOT NULL,
        FONE VARCHAR(20),
        FONE1 VARCHAR(20),
        FONE2 VARCHAR(20),
        PRIMARY KEY(CODCLI)
);
CREATE TABLE CLIENTE_VIP_REL
(
		CODCLI1 VARCHAR(15),
        PONTOS_BONIFICACAO INTEGER NOT NULL,
        DESCONTO_PADRAO VARCHAR(10),
       PRIMARY KEY (CODCLI1)
);
CREATE TABLE CLIENTE_ESPECIAL_REL
(
		CODCLI2 VARCHAR(15),
		DESCONTO_PADRAO VARCHAR(10),
		PRIMARY KEY (CODCLI2)
);
CREATE TABLE PEDIDO_REL
(
		CODPED VARCHAR(20) NOT NULL,
        DATA_PEDIDO DATE NOT NULL,
        DATA_ENTREGA DATE NOT NULL,
        RUA VARCHAR(100) NOT NULL,
        CIDADE VARCHAR(100) NOT NULL,
        ESTADO CHAR(2) NOT NULL,
        CEP CHAR(10) NOT NULL,
        CODCLI3 VARCHAR(15) NOT NULL,
        PRIMARY KEY (CODPED),
        Foreign key (CODCLI3)
			References Cliente_rel (CODCLI)
);
CREATE TABLE ITEM_PEDIDO_REL
(
		NO_ITEM VARCHAR(5) NOT NULL,
        CODPED1 VARCHAR(20) NOT NULL,
        QUANTIDADE DECIMAL(15,2),
        DESCONTO DECIMAL(5,2),
        CODMER1 Varchar(15),
        PRIMARY KEY (NO_ITEM),
        FOREIGN KEY (CODPED1)
			References PEDIDO_REL (CODPED),
		Foreign Key (Codmer1)
			References Mercadoria_Rel(Codmer)
);
CREATE TABLE MERCADORIA_REL
(
		CODMER VARCHAR(15),
        PRECO DECIMAL(15,2),
        ICMS VARCHAR(10),
        PRIMARY KEY (CODMER)
);